In [2]:
#Exercice 1
#Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

import numpy as np
vector = np.arange(21)
vector[9:16] *= -1

print(vector)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [3]:
#Exercice 2
#Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

import numpy as np
vector = np.arange(15, 56)
print(vector[1:-1])


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [4]:
#Exercice 3
#Write a NumPy program to create a 3X4 array and iterate over it.
import numpy as np
array_3x4 = np.array([[1, 6, 7, 4],
                      [5, 24, 7, 8],
                      [9, 60, 9, 12]])
for row in range(array_3x4.shape[0]):
    for col in range(array_3x4.shape[1]):
        print(f"Element at ({row}, {col}): {array_3x4[row, col]}")

Element at (0, 0): 1
Element at (0, 1): 6
Element at (0, 2): 7
Element at (0, 3): 4
Element at (1, 0): 5
Element at (1, 1): 24
Element at (1, 2): 7
Element at (1, 3): 8
Element at (2, 0): 9
Element at (2, 1): 60
Element at (2, 2): 9
Element at (2, 3): 12


In [5]:
#Exercice 4
#Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

import numpy as np
vector = np.linspace(5, 50, 10)
print(vector)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [7]:
#Exercice 5
#Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

import numpy as np
vector = np.random.randint(0, 11, 5)
print(vector)

[4 6 2 9 3]


In [8]:
#Exercice 6
#Write a NumPy program to multiply the values of two given vectors.

import numpy as np
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([5, 4, 3, 2, 1])
result = vector1 * vector2
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Element-wise multiplication result:", result)

Vector 1: [1 2 3 4 5]
Vector 2: [5 4 3 2 1]
Element-wise multiplication result: [5 8 9 8 5]


In [9]:
#Exercice 7
#Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

import numpy as np
matrix = np.arange(10, 22).reshape(3, 4)
print(matrix)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [10]:
#Exercice 8
#Write a NumPy program to find the number of rows and columns in a given matrix.

import numpy as np
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
num_rows, num_columns = matrix.shape
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 3
Number of columns: 3


In [11]:
#Exercice 9
#Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

import numpy as np
matrix = np.zeros((4, 4), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [12]:
#Exercice 10
#Write a NumPy program to find common values between two arrays.
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])
common_values = np.intersect1d(array1, array2)
print("Array1:", array1)
print("Array2:", array2)
print("Common values between two arrays:")
print(common_values)

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


In [13]:
#Exercice 11
#Write a NumPy program to get the unique elements of an array

import numpy as np
array1 = np.array([10, 10, 20, 20, 30, 30])
array2 = np.array([[1, 1], [2, 3]])
unique_array1 = np.unique(array1)
unique_array2 = np.unique(array2)

print("Original array:")
print(array1)
print("Unique elements of the above array:")
print(unique_array1)
print("Original array:")
print(array2)
print("Unique elements of the above array:")
print(unique_array2)


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [14]:
#Exercice 12
#Write a NumPy program to compute the cross product of two given vectors.

import numpy as np
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
cross_product = np.cross(vector1, vector2)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Cross product:", cross_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Cross product: [-3  6 -3]


In [16]:
#Exercice 13
#Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates.
import numpy as np
cartesian_coords = np.random.rand(10, 2)  
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.hypot(x, y)
theta = np.arctan2(y, x)
print(r)
print(theta)

[0.88216647 0.66734298 0.79271307 0.7690145  0.50902409 1.01257034
 0.73592848 0.82035337 0.21879353 0.83741156]
[1.11801838 0.86816649 1.02460611 0.53528706 0.69727559 1.18877666
 0.07789942 1.10896684 1.42940384 1.30520361]


In [22]:
#Exercice 14
#Write a NumPy program to find the closest value (to a given scalar) in an array.

import numpy as np
original_array = np.arange(100)
value_to_compare = 34.99062268928913
index_of_closest = np.abs(original_array - value_to_compare).argmin()
closest_value = original_array[index_of_closest]
print("Original array:")
print(original_array)
print("Value to compare:")
print(value_to_compare)
print("Closest value:")
print(closest_value)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
34.99062268928913
Closest value:
35
